jsonTest/urls.py
from django.conf.urls import url
from . import views

app_name = 'jsonTest'

urlpatterns = [
    url(r'^$', views.index, name='index')
]

short/urls.py
from django.conf.urls import url
from . import views

app_name = 'short'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^redirect/(?P<url_id>[0-9]+)/$', views.redirect, name='redirect'),
]

shorten/urls.py
from django.conf.urls import url
from . import views

app_name = 'shorten'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^submit/', views.submit, name="submit"),
    url(r'^redirect/(?P<url_id>[0-9]+)/$', views.redirect, name="redirect"),
]

urlShort/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^url/', include('ushort.urls')),
    url(r'^short/', include('short.urls')),
    url(r'^jtest/', include('jsonTest.urls')),
    url(r'^shorten/', include('shorten.urls')),
]

ushort/urls.py
from django.conf.urls import url
from . import views

app_name = 'ushort'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^(?P<url_id>[0-9]+)/create/$', views.create, name='create'),
    url(r'^(?P<url_id>[0-9]+)/$', views.redirect, name='redirect'),
]

jsonTest/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

short/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shorten/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ushort/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Urls(models.Model):
    original_url = models.CharField(max_length=3000)

    def __str__(self):
        return self.original_url

jsonTest/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import json
# Create your views here.



def index(request):
    response = {
        'hello': 'world',
        'foo': 'bar',
    }
    return HttpResponse(json.dumps(response), content_type='application/json', status=200)
    # return JsonResponse(response)

short/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from ushort.models import Urls
from django.core.urlresolvers import reverse
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.


def index(request):
    return render(request, 'short/index.html')


def submit(request):
    long_url = request.POST.get('url')
    q = Urls(original_url=long_url)
    q.save()
    url_id = q.id
    current_domain = get_current_site(request)
    new_url = "http://" + str(current_domain) + reverse('short:redirect', args=(url_id,))
    context = {
        'new_url': new_url,
    }
    return render(request, 'short/submit.html', context)


def redirect(request, url_id):
    url = Urls.objects.get(id=url_id)
    return HttpResponseRedirect(url.original_url)

shorten/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from ushort.models import Urls
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.


def index(request):
    return render(request, 'shorten/index.html')


@csrf_exempt
def submit(request):
    long_url = request.POST.get('url')
    q = Urls(original_url=long_url)
    q.save()
    url_id = q.id
    current_domain = get_current_site(request)
    current_url = "http://" + str(current_domain)
    print 'testing'
    print reverse('shorten:redirect', args=(url_id,))
    current_url = current_url + reverse('shorten:redirect', args=(url_id,))
    return HttpResponse(current_url)


def redirect(request, url_id):
    print 'redirect of shorten'
    url = Urls.objects.get(id=url_id)
    return HttpResponseRedirect(url.original_url)

ushort/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Urls
from django.core.urlresolvers import reverse
from django.contrib.sites.shortcuts import get_current_site

# Create your views here.


def index(request):
    return render(request, 'ushort/index.html')


def submit(request):
    long_url = request.POST.get('url')
    q = Urls(original_url=long_url)
    q.save()
    url_id = q.id
    return HttpResponseRedirect(reverse('ushort:create', args=(url_id,)))


def create(request, url_id):
    prev_url = Urls.objects.get(id=url_id)
    url_id = prev_url.id
    current_domain = get_current_site(request)
    if request.is_secure():
        our_protocol = "https://"
    else:
        our_protocol = "http://"
    current_url = our_protocol + str(current_domain) + reverse('ushort:redirect', args=(url_id,))
    context = {
        'current_url': current_url,
        'url_id': url_id
    }
    return render(request, 'ushort/create.html', context)


def redirect(request, url_id):
    url = Urls.objects.get(id=url_id)
    return HttpResponseRedirect(url.original_url)

templates/short/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Shortening</title>
    <link type="text/css" rel="stylesheet" href="{% static 'short/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'short/css/style.css' %}">
    <script src="{% static 'short/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'short/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <form class="form-inline" id="url_form" action="{% url 'short:submit' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="url">Enter a long url to make tiny</label>
            <input type="text" class="form-control" max="3000" name="url" id="url" />
        </div>
        <button type="submit" class="btn btn-info">Make Tiny Url!</button>
    </form>
</body>
</html>

templates/short/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <a href="{{ new_url }}">{{ new_url }}</a>
</body>
</html>

templates/shorten/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Shortening</title>
    <link type="text/css" rel="stylesheet" href="{% static 'shorten/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'shorten/css/style.css' %}">
    <script src="{% static 'shorten/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'shorten/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'shorten/js/style.js' %}"></script>
</head>
<body>
    <form class="form-inline" id="url_form">
        {% csrf_token %}
        <div class="form-group">
            <label for="url">Enter a long url to make tiny</label>
            <input type="text" class="form-control" max="3000" name="url" id="url" />
        </div>
        <button type="submit" class="btn btn-info">Make Tiny Url!</button>
    </form>
    <div class="progress" id="prog">
        <div class="progress-bar progress-bar-striped active" style="width:100%;">
        </div>
    </div>
    <p id="demo"></p>
</body>
</html>

templates/ushort/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{{ current_url }}">{{ current_url }}</a>
</body>
</html>

templates/ushort/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Shortner</title>
    <link type="text/css" rel="stylesheet" href="{% static 'ushort/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'ushort/css/style.css' %}">
    <script src="{% static 'ushort/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'ushort/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <form class="form-inline" id="url_form" action="{% url 'ushort:submit' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="url">Enter a long url to make tiny</label>
            <input type="text" class="form-control" max="3000" name="url" id="url" />
        </div>
        <button type="submit" class="btn btn-info">Make Tiny Url!</button>
    </form>
</body>
</html>